# experiment name
EXP_NAME: LI_SRGAN_pretrain_ship
# random number seed
SEED: 0
# super resolution magnification factor
SCALE: 4
# run device model
DEVICE_ID: 0

# Model define
MODEL:
  EMA:
    ENABLE: True
    DECAY: 0.999
    COMPILED: False # True
  G:
    NAME: srresnet_x4
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 64
    NUM_RCB: 16
    COMPILED: False # True

TRAIN:
  DATASET:
    TRAIN_GT_IMAGES_DIR: "/root/workspace/datasets/lightweight_SRGAN/ImageSize/out_image-size-256"

    # 论文中的 crop_size
    GT_IMAGE_SIZE: 256

  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    PRETRAINED_G_MODEL: ""
    RESUMED_G_MODEL: ""

  # training hyperparameters
  HYP:
    # 预训练的 Epochs (可以设为 100)
    EPOCHS: 100

    IMGS_PER_BATCH: 16
    SHUFFLE: True
    NUM_WORKERS: 0 # 解决共享内存不足问题，原始为4.(由数据加载器的工作进程数量引起的)?
    # 强制关闭 pin_memory，进一步减少内存压力
    PIN_MEMORY: False  # 原来为true
    # 强制关闭 persistent_workers，因为 num_workers 已经是 0
    PERSISTENT_WORKERS: False # 原来为true

  OPTIM:
    NAME: Adam
    # 学习率
    LR: 1.0e-3 # 0.001
    # !! 注意 !! 
    # 预训练使用标准的 Adam 参数，不要用论文里的 [0.0, 0.9]
    BETAS: [0.9, 0.999]
    EPS: 0.00000001
    WEIGHT_DECAY: 0.0

  # Loss function
  LOSSES:
    PIXEL_LOSS:
      NAME: MSELoss
      WEIGHT: [1.0]

  PRINT_FREQ: 100

TEST:
  DATASET:
    PAIRED_TEST_GT_IMAGES_DIR: "/root/workspace/datasets/lightweight_SRGAN/val_hr_256"
    PAIRED_TEST_LR_IMAGES_DIR: "/root/workspace/datasets/lightweight_SRGAN/val_lr_64"

  # Test hyperparameters
  HYP:
    IMGS_PER_BATCH: 1
    SHUFFLE: False
    NUM_WORKERS: 1
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

  # Only test Y channel
  ONLY_TEST_Y_CHANNEL: True

  SAVE_IMAGE_DIR: ""
